# Generated by Django 4.2.7 on 2023-11-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="graphmodel",
            name="X_value",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="graphmodel",
            name="Xlabel",
            field=models.CharField(
                default=0, help_text="Enter x-axis label", max_length=20
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="graphmodel",
            name="Y_value",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="graphmodel",
            name="Ylabel",
            field=models.CharField(
                default=0, help_text="Enter y-axis label", max_length=20
            ),
            preserve_default=False,
        ),
    ]
