# Generated by Django 5.0.1 on 2024-03-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0002_alter_excelfile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="excelfile",
            name="x_values",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="excelfile",
            name="y_values",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
