# Generated by Django 4.2.7 on 2023-11-14 17:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0002_graphmodel_x_value_graphmodel_xlabel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="graphmodel",
            name="X_value",
        ),
        migrations.RemoveField(
            model_name="graphmodel",
            name="Y_value",
        ),
    ]
