# Generated by Django 5.0.1 on 2024-04-02 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_excelfile_x_values_excelfile_y_values'),
        ('graph', '0005_graphpoint_delete_xaxis'),
    ]

    operations = [
    ]
