# Generated by Django 4.2.7 on 2023-11-14 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("graph", "0003_remove_graphmodel_x_value_remove_graphmodel_y_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="Xaxis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Xvalue", models.IntegerField(blank=True, null=True)),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Graph_Name",
                        to="graph.graphmodel",
                    ),
                ),
            ],
        ),
    ]
